apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  type: NodePort
  selector:
    app: angular-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}
